/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import logica.GestorPrincipal;
import org.openide.util.Exceptions;

/**
 *
 * @author gnord
 */
public class MainPantallaPrincipalCorredor extends javax.swing.JFrame {

    private File f = new File("/imagenes/corredor.png");
    private static final String RUTA_LOGO = "/imagenes/corredor.png";

    /**
     * Creates new form MainCorredor
     */
    public MainPantallaPrincipalCorredor() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor corredores");
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        GestorPrincipal.getInstance().volcarCsvCorredoresAColeccion();

        try {
            Image image = ImageIO.read(getClass().getResource(RUTA_LOGO));
            image = image.getScaledInstance(100,100, Image.SCALE_SMOOTH);
            jLabelIcono.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }

        //metodo para guardar la coleccion si se cierra en la cruz el programa
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                GestorPrincipal.getInstance().grabarColeccionCorredoresAcsv();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemAltaCorredor = new javax.swing.JMenuItem();
        jMenuItemAltaCarrera = new javax.swing.JMenuItem();
        jMenuItemVisualCorredor = new javax.swing.JMenuItem();
        jMenuVerCarreras = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenuPrincipal.setText("Menu");

        jMenuItemAltaCorredor.setText("Alta Corredor");
        jMenuItemAltaCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaCorredorActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemAltaCorredor);

        jMenuItemAltaCarrera.setText("Alta Carrera");
        jMenuItemAltaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaCarreraActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemAltaCarrera);

        jMenuItemVisualCorredor.setText("Ver Corredores");
        jMenuItemVisualCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualCorredorActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemVisualCorredor);

        jMenuVerCarreras.setText("Ver Carreras");
        jMenuPrincipal.add(jMenuVerCarreras);

        jMenuBar1.add(jMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAltaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaCarreraActionPerformed
        FormularioAltaCarreras formularioCarrera = new FormularioAltaCarreras(this, true);
        formularioCarrera.setVisible(true);
    }//GEN-LAST:event_jMenuItemAltaCarreraActionPerformed

    private void jMenuItemAltaCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaCorredorActionPerformed
        FormularioAltaCorredor formulario = new FormularioAltaCorredor(this, true);
        formulario.setVisible(true);
        //poner rellenar lista
    }//GEN-LAST:event_jMenuItemAltaCorredorActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        GestorPrincipal.getInstance().grabarColeccionCorredoresAcsv();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuItemVisualCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualCorredorActionPerformed
        VisualizadorCorredores visCorredores = new VisualizadorCorredores(this, true);
        visCorredores.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualCorredorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPantallaPrincipalCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPantallaPrincipalCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPantallaPrincipalCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPantallaPrincipalCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPantallaPrincipalCorredor().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAltaCarrera;
    private javax.swing.JMenuItem jMenuItemAltaCorredor;
    private javax.swing.JMenuItem jMenuItemVisualCorredor;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenu jMenuVerCarreras;
    // End of variables declaration//GEN-END:variables
}
