/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import logica.GestorPrincipal;
import logica.TableModelCarrera;
import logica.TableModelCorredor;
import logica.TableModelCorredorCarrera;
import modelo.Carrera;
import modelo.Corredor;
import modelo.CorredorCarrera;

/**
 *
 * @author daniel regueiro
 */
public class VisualizadorCarreras extends javax.swing.JDialog {

    /**
     * Creates new form VisualizadorCarreras
     */
    public VisualizadorCarreras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarTable();
        rellenarTableDisponibles();
    }

    public void rellenarTable() {

        jTableCarreras.setModel(new TableModelCarrera(GestorPrincipal.getInstance().devolverColeccionCarreras()));

    }

    public void rellenarTableDisponibles() {

        jTableCorredoresDisponibles.setModel(new TableModelCorredor(GestorPrincipal.getInstance().devolverColeccionCorredores()));

    }

    public void rellenarTableCorredoresCarrera() {

        jTableCorredoresCarrera.setModel(new TableModelCorredorCarrera(carreraSeleccionada().getCorredores()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelParticipantes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredoresCarrera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jLabelTituloCarreras = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonEliminarCorredor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCorredoresDisponibles = new javax.swing.JTable();
        jLabelParticipantes1 = new javax.swing.JLabel();
        jButtonAnadirCorredor = new javax.swing.JButton();
        jButtonEliminarCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelParticipantes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelParticipantes.setText("Participantes:");

        jTableCorredoresCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCorredoresCarrera);

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCarreras);

        jLabelTituloCarreras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloCarreras.setText("Carrera:");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonEliminarCorredor.setText("Eliminar Corredor");
        jButtonEliminarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCorredorActionPerformed(evt);
            }
        });

        jTableCorredoresDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCorredoresDisponibles);

        jLabelParticipantes1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelParticipantes1.setText("Corredores disponibles:");

        jButtonAnadirCorredor.setText("Añadir Corredor");
        jButtonAnadirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirCorredorActionPerformed(evt);
            }
        });

        jButtonEliminarCarrera.setText("Eleminar Carrera");
        jButtonEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelParticipantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(489, 489, 489))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTituloCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAnadirCorredor)
                    .addComponent(jButtonEliminarCarrera)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarCorredor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelParticipantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnadirCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCarreraActionPerformed
        int seleccionado = jTableCarreras.getSelectedRow();
        if (seleccionado >= 0) {
            Carrera carrera = GestorPrincipal.getInstance().devolverColeccionCarreras().get(seleccionado);
            GestorPrincipal.getInstance().eleminarCarrera(carrera.getIdentificador());
            this.rellenarTable();
        }
    }//GEN-LAST:event_jButtonEliminarCarreraActionPerformed
    public Carrera carreraSeleccionada() {
        Carrera carrera = null;
        int seleccionad = jTableCarreras.getSelectedRow();
        if (seleccionad >= 0) {
            carrera = GestorPrincipal.getInstance().devolverColeccionCarreras().get(seleccionad);

        }
        return carrera;
    }
    private void jButtonAnadirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirCorredorActionPerformed
        int corredorSeleccionado = jTableCorredoresDisponibles.getSelectedRow();
        Corredor corredor = null;
        CorredorCarrera corrCarr;
        if (corredorSeleccionado >= 0) {
            corredor = GestorPrincipal.getInstance().devolverColeccionCorredores().get(corredorSeleccionado);
        }
        int dorsal = 1;

        int carreraSeleccionada = jTableCarreras.getSelectedRow();
        if (carreraSeleccionada >= 0) {
            Carrera carrera = carreraSeleccionada();
            dorsal = carrera.getCorredores().size() + 1;
            corrCarr = new CorredorCarrera(corredor, dorsal);
            carrera.getCorredores().add(corrCarr);

            jTableCorredoresCarrera.setModel(new TableModelCorredorCarrera(carreraSeleccionada().getCorredores()));
        }
        this.rellenarTable();
        this.rellenarTableDisponibles();
    }//GEN-LAST:event_jButtonAnadirCorredorActionPerformed

    private void jButtonEliminarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCorredorActionPerformed
       int corredorSeleccionado = jTableCorredoresCarrera.getSelectedRow();  
        
        
        
        
    }//GEN-LAST:event_jButtonEliminarCorredorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirCorredor;
    private javax.swing.JButton jButtonEliminarCarrera;
    private javax.swing.JButton jButtonEliminarCorredor;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelParticipantes;
    private javax.swing.JLabel jLabelParticipantes1;
    private javax.swing.JLabel jLabelTituloCarreras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableCorredoresCarrera;
    private javax.swing.JTable jTableCorredoresDisponibles;
    // End of variables declaration//GEN-END:variables
}
