package Componentes;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import twitter4j.MediaEntity;
import twitter4j.Status;

public class ComponenteTweet extends javax.swing.JPanel {

    private Status tweet;

    public ComponenteTweet() {
        initComponents();
    }

    public void cargarTweet(Status tweet) {
        this.tweet = tweet;
        cargarDatos();
        cargarImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAvatar = new javax.swing.JLabel();
        jScrollPaneTweet = new javax.swing.JScrollPane();
        jTextAreaTweet = new javax.swing.JTextArea();
        jLabelScreenName = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();

        jLabelAvatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPaneTweet.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTweet.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneTweet.setNextFocusableComponent(jTextAreaTweet);

        jTextAreaTweet.setColumns(20);
        jTextAreaTweet.setRows(5);
        jTextAreaTweet.setAutoscrolls(false);
        jTextAreaTweet.setPreferredSize(null);
        jScrollPaneTweet.setViewportView(jTextAreaTweet);

        jLabelScreenName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelScreenName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelScreenName.setText("@dam2twitter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelScreenName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelScreenName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTweet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        jTextAreaTweet.setLineWrap(true);   //scroll horizontal desactivado
        jTextAreaTweet.setWrapStyleWord(true);  //evita la partición de palabras
        jLabelScreenName.setText("@" + this.tweet.getUser().getScreenName());
        String texto = tweet.getText();
        int lineas = 0;
        String[] numLineas = texto.split("\n");
        lineas += numLineas.length;
        for (String numLinea : numLineas) {
            if (numLinea.length() > 30) {
                lineas += numLinea.length() / 30;
            }
        }
        jTextAreaTweet.setRows(lineas);
        jTextAreaTweet.setText(tweet.getText());
    }

    private void cargarImagenes() {
        try {
            //avatar
            ImageIcon avatar = new ImageIcon(new URL(tweet.getUser().getOriginalProfileImageURL()));
            jLabelAvatar.setSize(50, 50);
            Image avatarEscalado = avatar.getImage().getScaledInstance(jLabelAvatar.getWidth(), jLabelAvatar.getHeight(), Image.SCALE_DEFAULT);
            avatar.setImage(avatarEscalado);
            jLabelAvatar.setIcon(avatar);
            //multimedia
            if (tweet.getMediaEntities().length == 0) {
                jLabelImagen.setVisible(false);
            } else {
                MediaEntity mediaEntity = tweet.getMediaEntities()[0];
                if (mediaEntity.getType().equals("photo")) {
                    ImageIcon imagenTweet = new ImageIcon(new URL(mediaEntity.getMediaURL()));
                    double cocienteProporcion = (double)imagenTweet.getIconWidth() / 300;
                    int altoProporcionado = (int) Math.round((double) imagenTweet.getIconHeight() / cocienteProporcion);
                    Image imagenTweetEscalada = imagenTweet.getImage().getScaledInstance(300, altoProporcionado, Image.SCALE_DEFAULT);
                    imagenTweet.setImage(imagenTweetEscalada);
                    jLabelImagen.setIcon(imagenTweet);
                }
            }
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelScreenName;
    private javax.swing.JScrollPane jScrollPaneTweet;
    private javax.swing.JTextArea jTextAreaTweet;
    // End of variables declaration//GEN-END:variables
}
