package logica;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Timer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author daniel
 */
public class CronoCarrera extends javax.swing.JPanel implements Serializable {

    private Integer minutos = 0, segundos = 0, milesimas = 0;
    private List<logica.EventoLisenerCrono> listeners = new ArrayList();
    private String min = "", seg = "", mil = "";
    private String dorsal;
    private String tiempo;
    private Timer timer = new Timer(1, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            milesimas++;

            if (milesimas == 1000) {
                milesimas = 0;
                segundos += 1;

                if (segundos == 60) {
                    segundos = 0;
                    minutos++;
                }
            }

            if (minutos < 10) {
                min = "0" + minutos;
            } else {
                min = minutos.toString();
            }
            if (segundos < 10) {
                seg = "0" + segundos;
            } else {
                seg = segundos.toString();
            }

            if (milesimas < 10) {
                mil = "00" + milesimas;
            } else if (milesimas < 100) {
                mil = "0" + milesimas;
            } else {
                mil = milesimas.toString();
            }

            jLabelCronometro.setText(min + ":" + seg + ":" + mil);

        }
    });

    /**
     * Creates new form Cronometro
     */
    public CronoCarrera() {
        initComponents();
        jLabelCronometro.setText("00:00:000");
    }

    public void start() {

        timer.start();

    }
public void anadirLisener(EventoLisenerCrono lisener){
listeners.add(lisener);


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCronometro = new javax.swing.JLabel();
        botonAsignarTiempo = new javax.swing.JButton();
        botonPlay = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        botonStop = new javax.swing.JButton();

        jLabelCronometro.setBackground(new java.awt.Color(0, 102, 0));
        jLabelCronometro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelCronometro.setForeground(new java.awt.Color(0, 204, 0));
        jLabelCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCronometro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonAsignarTiempo.setText("Asignar tiempo ");
        botonAsignarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarTiempoActionPerformed(evt);
            }
        });

        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoPlay.png"))); // NOI18N
        botonPlay.setText("Play");
        botonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stop.png"))); // NOI18N
        botonStop.setText("Stop");
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAsignarTiempo)
                    .addComponent(botonStop))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAsignarTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        if (!timer.isRunning()) {
            start();
        }
    }//GEN-LAST:event_botonPlayActionPerformed

    private void botonAsignarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarTiempoActionPerformed
        dorsal = jTextField1.getText();
        tiempo = jLabelCronometro.getText();
        for (logica.EventoLisenerCrono l : listeners) {
            l.ejecutar(dorsal, tiempo);
        }
    }//GEN-LAST:event_botonAsignarTiempoActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        timer.stop();
    }//GEN-LAST:event_botonStopActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignarTiempo;
    private javax.swing.JButton botonPlay;
    private javax.swing.JButton botonStop;
    private javax.swing.JLabel jLabelCronometro;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
